export const types = {
  LOGIN: 'LOGIN',
  SAVE_QUESTION: 'SAVE_QUESTION',
  CHANGE_QUESTION: 'CHANGE_QUESTION',
  FETCH_COURSES: 'FETCH_COURSES',
  SET_ROLES: 'SET_ROLES',
  SET_ROLE_ID: 'SET_ROLE_ID',
};
